FB-435 new transactions for orders
rarible/flow-contracts pull request #32
Opened 2021-11-25 09:25 UTC by zolt

2021-11-25 10:09 UTC, zhalninde requested changes

2021-11-25 10:09 UTC, zhalninde commented on transactions/storefront/sell.cdc
> +import RaribleNFT from "../../../contracts/RaribleNFT.cdc" //template
импорты надо поправить

2021-11-25 10:09 UTC, zhalninde commented on transactions/storefront/update_price.cdc
> +    originFees: {Addres: UFix64}, //additional fees from other marketplace etc.
%s/Addres/Address/g

2021-11-25 10:09 UTC, zhalninde commented on transactions/storefront/update_price.cdc
> +import RaribleNFT from "../../../contracts/RaribleNFT.cdc" //template
тоже импорты, не проходит компиляцию

2021-11-25 10:47 UTC, zolt commented on transactions/storefront/buy.cdc
> +transaction(orderId: UInt64, storefrontAddress: Address, fees: {Addres: UFix64}) {
пофиксил, вроде везде

2021-11-26 14:17 UTC, vitalbadjo commented on transactions/storefront/buy.cdc
> +    let feeReceivers: {Capability<&{FungibleToken.Receiver}>: UFix64}
this line throw error: cannot use type as dictionary key type: `Capability<&AnyResource{FungibleToken.Receiver}>`
18 |     let feeReceivers: {Capability<&{FungibleToken.Receiver}>: UFix64}
     |.                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2021-11-26 14:19 UTC, vitalbadjo commented on transactions/storefront/buy.cdc
> +    let paymentVault: @FungibleToken.Vault
error: cannot use incompletely initialized value: `self`
  --> d4251a0c407d491f9c38910efbb31cdaa152a2c2983e0951f6913e0 ...  `paymentVault` of type `Transaction` is not invalidated (moved or destroyed)
  --> d4251a0c407d491f9c38910efbb31cdaa152a2c2983e0951f6913e0beb607111:14:8
   |
14 |     let paymentVault: @FungibleToken.Vault
   |         ^^^^^^^^^^^^ not invalidated

2021-11-29 05:50 UTC, vitalbadjo commented on transactions/storefront/buy.cdc
> +        let price = self.listing.getDetails().salePrice
has no member listing, "self" is redundant

2021-12-03 06:43 UTC, atapin approved these changes

2021-12-03 09:21 UTC, zhalninde approved these changes

2021-12-03 09:21 UTC, merged